### ISSUE TITLE
Use of capture_output prevents poetryup working on Python3.6

### ISSUE THREAD

**Issue by codedstructure** [MousaZeidBaker/poetryup#45]
Running on Python3.6 (from CentOS7) gives an error when running poetryup due to use of `capture_output` in `subprocess.run()`

```
[root@4afe8249a4b5 src]# poetry run poetryup --latest --skip-exact
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/xxxxxx-VsnhxLU2-py3.6/bin/poetryup", line 8, in <module>
    sys.exit(app())
  File "/root/.cache/pypoetry/virtualenvs/xxxxxx-VsnhxLU2-py3.6/lib/python3.6/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/xxxxxx-VsnhxLU2-py3.6/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/xxxxxx-VsnhxLU2-py3.6/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/xxxxxx-VsnhxLU2-py3.6/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.cache/pypoetry/virtualenvs/xxxxxx-VsnhxLU2-py3.6/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/xxxxxx-VsnhxLU2-py3.6/lib/python3.6/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/root/.cache/pypoetry/virtualenvs/xxxxxx-VsnhxLU2-py3.6/lib/python3.6/site-packages/poetryup/main.py", line 37, in poetryup
    pyproject = Pyproject(pyproject_str)
  File "/root/.cache/pypoetry/virtualenvs/xxxxxx-VsnhxLU2-py3.6/lib/python3.6/site-packages/poetryup/core/pyproject.py", line 25, in __init__
    self.poetry_version = version_.parse(self.__get_poetry_version())
  File "/root/.cache/pypoetry/virtualenvs/xxxxxx-VsnhxLU2-py3.6/lib/python3.6/site-packages/poetryup/core/pyproject.py", line 241, in __get_poetry_version
    capture_output=True,
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

**Comment by MousaZeidBaker** [comment]
Yeah `capture_output` was introduced in 3.7. Fix on its way.

**Comment by codedstructure** [comment]
thanks for the prompt fix!
